// AUTO-GENERATED by web/scripts/derive-facts.mjs at prebuild.
// DO NOT EDIT — re-run `npm run prebuild` (or just `npm run build`) after changing the parent repo.
// To override at runtime, write the same shape to KV under key "facts:current".

export interface ProviderFact { id: string; label: string; env: string }

export interface RepoFacts {
  generatedAt: string;
  version: string | null;
  crates: string[];
  sandboxBackends: string[];
  providers: ProviderFact[];
  defaultModel: string | null;
  nodeEngines: string | null;
  toolCount: number | null;
  license: string | null;
  latestRelease: string | null;
}

export const FACTS: RepoFacts = {
  "generatedAt": "2026-09-13T13:37:43.466Z",
  "version": "0.1.0",
  "crates": [
    "agent",
    "agent-runtime",
    "app-server",
    "cli",
    "config",
    "core",
    "execpolicy",
    "extensions",
    "extensions-fixture-dylib",
    "hooks",
    "index",
    "mcp",
    "protocol",
    "providers",
    "release",
    "secrets",
    "state",
    "tool-impls",
    "tools",
    "tui",
    "tui-core"
  ],
  "sandboxBackends": [
    "runtime"
  ],
  "providers": [
    {
      "id": "deepseek",
      "label": "DeepSeek",
      "env": "DEEPSEEK_API_KEY"
    },
    {
      "id": "nvidia-nim",
      "label": "NVIDIA NIM",
      "env": "NVIDIA_API_KEY / NVIDIA_NIM_API_KEY"
    },
    {
      "id": "openai",
      "label": "OpenAI-compatible",
      "env": "OPENAI_API_KEY"
    },
    {
      "id": "atlascloud",
      "label": "AtlasCloud",
      "env": "ATLASCLOUD_API_KEY"
    },
    {
      "id": "wanjie-ark",
      "label": "Wanjie Ark",
      "env": "WANJIE_ARK_API_KEY / WANJIE_API_KEY / WANJIE_MAAS_API_KEY"
    },
    {
      "id": "volcengine",
      "label": "Volcengine Ark",
      "env": "VOLCENGINE_API_KEY / VOLCENGINE_ARK_API_KEY / ARK_API_KEY"
    },
    {
      "id": "openrouter",
      "label": "OpenRouter",
      "env": "OPENROUTER_API_KEY"
    },
    {
      "id": "xiaomi-mimo",
      "label": "Xiaomi MiMo",
      "env": "XIAOMI_MIMO_API_KEY / XIAOMI_API_KEY / MIMO_API_KEY"
    },
    {
      "id": "novita",
      "label": "Novita AI",
      "env": "NOVITA_API_KEY"
    },
    {
      "id": "fireworks",
      "label": "Fireworks AI",
      "env": "FIREWORKS_API_KEY"
    },
    {
      "id": "siliconflow",
      "label": "SiliconFlow",
      "env": "SILICONFLOW_API_KEY"
    },
    {
      "id": "moonshot",
      "label": "Moonshot/Kimi",
      "env": "MOONSHOT_API_KEY / KIMI_API_KEY"
    },
    {
      "id": "sglang",
      "label": "SGLang",
      "env": "SGLANG_API_KEY"
    },
    {
      "id": "vllm",
      "label": "vLLM",
      "env": "VLLM_API_KEY"
    },
    {
      "id": "ollama",
      "label": "Ollama",
      "env": "OLLAMA_API_KEY"
    },
    {
      "id": "anthropic",
      "label": "Anthropic",
      "env": "ANTHROPIC_API_KEY"
    }
  ],
  "defaultModel": "deepseek-v4-pro",
  "nodeEngines": ">=18",
  "toolCount": 41,
  "license": "MIT",
  "latestRelease": null
};
