#!/usr/bin/env python3
"""Capability graph generator (startup-trio item 2, discipline 2).

A capability seam is a triple: a trait DEFINITION (in a framework crate),
a PROVIDER (a crate implementing it), and a CONSUMER (a crate using it as
a trait object). This script scans the workspace for the curated seam list
and regenerates docs/CAPABILITY_GRAPH.md so a missing role is visible.

Heuristics (a starting point, deliberately dumb):
- definition  = crate containing `pub trait <Name>`
- providers   = crates containing an `impl ... <Name> for` block
- consumers   = crates referencing `dyn <Name>` (trait-object use)

Test-module impls count as providers (noise accepted); if a seam ever
needs precision, teach this script. `--check` compares the generated
document with the committed one and exits non-zero on drift (CI gate —
regenerate with `python3 scripts/capability-graph.py`).
"""

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "docs" / "CAPABILITY_GRAPH.md"

# The curated seam list — capability traits with the definition/provider/
# consumer triple. Add a row here when landing a new capability (that is
# the discipline-2 admission check); the script fills in the roles.
SEAMS = [
    "AgentExecutor",
    "ChatHistory",
    "CommandDefinition",
    "Extension",
    "Handler",
    "HostServices",
    "IndexBackend",
    "IndexBackendFactory",
    "IndexServiceApi",
    "KeyringStore",
    "LlmClient",
    "ProviderFactory",
    "SandboxBackend",
    "ToolDefinition",
]

HEADER = """\
# Capability Graph (generated)

> Generated by `scripts/capability-graph.py` — do not hand-edit.
> Regenerate with `python3 scripts/capability-graph.py`; CI verifies
> freshness with `--check`.

A capability seam is a triple (discipline 2): **definition** (the trait, in
a framework crate) / **provider** (a crate implementing it) / **consumer**
(a crate using it). A new capability lands all three roles in the same
change; this table makes a missing role visible. `—` marks an empty role:
for intra-crate seams (definition and provider colocated, e.g.
`IndexBackend`) that is expected; for a cross-crate seam it is a gap worth
explaining.

| Seam trait | Definition | Providers | Consumers (`dyn` use) |
|---|---|---|---|
"""


def crate_of(path: Path) -> str:
    # crates/<crate>/src/... → <crate> with the codesmith- prefix stripped.
    return path.relative_to(REPO_ROOT).parts[1].removeprefix("codesmith-")


def scan() -> list[tuple[str, str, list[str], list[str]]]:
    # Read every source once and reuse the text across all seams (the seam
    # count multiplies the tree walk otherwise).
    sources = [
        (crate_of(p), p.read_text(encoding="utf-8", errors="replace"))
        for p in (REPO_ROOT / "crates").glob("*/src/**/*.rs")
        if "target" not in p.parts
    ]
    rows = []
    for seam in SEAMS:
        definition = None
        providers: set[str] = set()
        consumers: set[str] = set()
        impl_re = re.compile(rf"\bimpl\s*(?:<[^>]*>\s*)?{seam}\s+for\b")
        def_re = re.compile(rf"\bpub trait {seam}\b")
        dyn_re = re.compile(rf"\bdyn {seam}\b")
        for crate, text in sources:
            if def_re.search(text):
                definition = crate
            if impl_re.search(text):
                providers.add(crate)
            if dyn_re.search(text):
                consumers.add(crate)
        rows.append(
            (
                seam,
                definition or "—",
                sorted(providers) or ["—"],
                sorted(consumers) or ["—"],
            )
        )
    rows.sort(key=lambda r: r[0].lower())
    return rows


def render(rows: list[tuple[str, str, list[str], list[str]]]) -> str:
    out = [HEADER]
    for seam, definition, providers, consumers in rows:
        out.append(
            f"| `{seam}` | `{definition}` | "
            f"{', '.join(f'`{c}`' for c in providers)} | "
            f"{', '.join(f'`{c}`' for c in consumers)} |\n"
        )
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="verify the committed graph is fresh instead of writing it",
    )
    args = ap.parse_args()

    generated = render(scan())
    if args.check:
        committed = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.exists() else ""
        if committed != generated:
            print("error: docs/CAPABILITY_GRAPH.md is stale; regenerate with")
            print("  python3 scripts/capability-graph.py")
            return 1
        print(f"capability graph fresh ({len(SEAMS)} seams)")
        return 0

    OUT_PATH.write_text(generated, encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)} ({len(SEAMS)} seams)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
