#!/usr/bin/env python3
"""Bilingual docs-pair guard.

AGENTS.md: "Docs are maintained in bilingual pairs (`X.md` + `X_cn.md`) —
update both or neither." This guard makes drift visible instead of
relying on review: every top-level guide in docs/ must carry its _cn twin,
and every _cn file its base file.

Checked: docs/*.md at the top level only. Subdirectories are out of
scope — docs/legacy/ is upstream archival material, docs/superpowers/
holds generated workflow artifacts, docs/examples/ carries no prose.
Exempt: the allowlist below, one reason per file. Landing a _cn pair (or
deleting the file) removes an entry; adding an entry needs a reason.

Run from anywhere: `python3 scripts/verify-docs-pairs.py`.
Prints one line per violation and exits non-zero.
"""

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

ALLOWLIST = {
    "CAPABILITY_GRAPH.md": "generated by scripts/capability-graph.py",
    "CLI.md": "legacy unpaired; land a _cn pair to remove",
    "DESIGN_INTERNALS.md": "legacy unpaired; land a _cn pair to remove",
    "HARNESS.md": "legacy unpaired; land a _cn pair to remove",
}


def main() -> int:
    parser = argparse.ArgumentParser(description="Bilingual docs-pair guard.")
    parser.add_argument(
        "--root",
        type=Path,
        default=REPO_ROOT,
        help="repository root to scan (default: this script's repo)",
    )
    args = parser.parse_args()
    docs = args.root / "docs"

    violations: list[str] = []
    pairs = 0
    allowlisted = 0
    for path in sorted(docs.glob("*.md")):
        name = path.name
        if name.endswith("_cn.md"):
            base = docs / f"{name[: -len('_cn.md')]}.md"
            if not base.exists():
                violations.append(
                    f"{name}: _cn file without its base {base.name}"
                )
        elif name in ALLOWLIST:
            allowlisted += 1
        elif not (docs / f"{name[: -len('.md')]}_cn.md").exists():
            violations.append(
                f"{name}: no _cn pair — update both or neither "
                "(pair it, or add to the allowlist with a reason)"
            )
        else:
            pairs += 1

    for line in violations:
        print(line)
    if violations:
        print(f"docs pairs: {len(violations)} violation(s)")
        return 1
    print(f"docs pairs ok: {pairs} pair(s), {allowlisted} allowlisted")
    return 0


if __name__ == "__main__":
    sys.exit(main())
