//! Session state management for the core engine.
//!
//! Tracks conversation history, token usage, and session metadata.

use crate::compaction::circuit_breaker::CompactionCircuitBreaker;
use crate::compaction::micro_compact::MicroCompactState;
use crate::compaction::responsive_compact::ResponsiveCompactState;
use crate::compaction::session_memory_compact::SessionMemoryCompactConfig;
use crate::cycle_manager::CycleBriefing;
use crate::models::{Message, SystemPrompt, Usage};
use crate::prefix_cache::PrefixStabilityManager;
use crate::project_context::{ProjectContext, load_project_context_with_parents};
use crate::mode::ApprovalMode;
use crate::working_set::WorkingSet;
use chrono::{DateTime, Utc};
use serde_json::Value;
use std::collections::VecDeque;
use std::path::PathBuf;

const RECENT_READ_FILE_LIMIT: usize = 12;
const RECENT_READ_FILE_SNIPPET_CHARS: usize = 1_200;

/// Bounded snapshot of successful `read_file` tool outputs that may be lost
/// when old tool-result messages are compacted away.
#[derive(Debug, Clone)]
pub struct RecentReadFile {
    pub path: String,
    pub input: Value,
    pub output_preview: String,
}

/// Session state for the engine.
#[derive(Debug, Clone)]
pub struct Session {
    /// Model being used
    pub model: String,

    /// Reasoning-effort tier for DeepSeek thinking mode:
    /// `"off" | "low" | "medium" | "high" | "max"`. `None` lets the provider
    /// apply its own defaults.
    pub reasoning_effort: Option<String>,
    /// Whether the user selected automatic reasoning effort.
    pub reasoning_effort_auto: bool,

    /// Whether the user selected automatic model routing.
    pub auto_model: bool,

    /// Workspace directory
    pub workspace: PathBuf,

    /// Effective working directory. Normally equal to `workspace`,
    /// but shifts to a worktree path after `enter_worktree`.
    pub cwd: PathBuf,

    /// System prompt (optional)
    pub system_prompt: Option<SystemPrompt>,
    /// True when `system_prompt` came from an explicit runtime API override
    /// and should not be replaced by mode/context refreshes.
    pub system_prompt_override: bool,
    /// Hash of the last assembled stable system prompt. Used to avoid
    /// replacing `system_prompt` when unchanged.
    pub last_system_prompt_hash: Option<u64>,
    /// Persisted summary blocks generated by context compaction.
    pub compaction_summary_prompt: Option<SystemPrompt>,

    /// Conversation history (API format)
    pub messages: Vec<Message>,

    /// Successful recent `read_file` outputs, retained outside the transcript so
    /// compaction can re-inject concise file context without synthetic tool blocks.
    pub recent_read_files: VecDeque<RecentReadFile>,

    /// Total tokens used in this session
    pub total_usage: SessionUsage,

    /// Whether shell execution is allowed
    pub allow_shell: bool,

    /// Whether to trust paths outside workspace
    pub trust_mode: bool,

    /// Whether the current session should auto-approve tool safety checks.
    pub auto_approve: bool,

    /// Live UI approval policy used to steer the system prompt.
    pub approval_mode: ApprovalMode,

    /// Notes file path
    pub notes_path: PathBuf,

    /// MCP config path
    pub mcp_config_path: PathBuf,

    /// Session ID (for tracking)
    pub id: String,

    /// Project context loaded from AGENTS.md, etc.
    pub project_context: Option<ProjectContext>,

    /// Repo-aware working set for context management.
    pub working_set: WorkingSet,

    /// Number of cycle boundaries crossed in this session (issue #124). The
    /// active cycle index is `cycle_count + 1` (cycles are 1-based for users).
    pub cycle_count: u32,

    /// UTC start time of the *current* cycle. Updated when the engine resets
    /// the conversation buffer. Used by archive headers and the `/cycles`
    /// command's display.
    pub current_cycle_started: DateTime<Utc>,

    /// Briefings produced at past cycle boundaries, in chronological order.
    /// Bounded growth: one entry per cycle, briefing capped at ~3,000 tokens.
    pub cycle_briefings: Vec<CycleBriefing>,

    /// Prefix-cache stability monitor (inspired by Reasonix's Pillar 1).
    /// Tracks the immutable prefix fingerprint and detects drift across turns.
    /// Set during engine construction; None until the first system prompt assembly.
    pub prefix_stability: Option<PrefixStabilityManager>,

    /// Micro-compact state tracking (time triggers, bytes cleared).
    pub micro_compact_state: MicroCompactState,
    /// Session memory compact configuration (token retention bounds).
    pub session_memory_compact_config: SessionMemoryCompactConfig,
    /// Circuit breaker for auto-compaction (prevents infinite retry loops).
    pub circuit_breaker: CompactionCircuitBreaker,
    /// Responsive compact state (consecutive overflow tracking).
    pub responsive_compact_state: ResponsiveCompactState,
}

/// Cumulative usage statistics for a session.
#[derive(Debug, Clone, Default)]
#[allow(clippy::struct_field_names)]
pub struct SessionUsage {
    pub input_tokens: u64,
    pub output_tokens: u64,
    /// Cache creation (miss) tokens. `None` when never observed by the API —
    /// do NOT display as 0, which would be indistinguishable from "no misses".
    pub cache_creation_input_tokens: Option<u64>,
    /// Cache read (hit) tokens. `None` when never observed by the API —
    /// do NOT display as 0, which would be indistinguishable from "no hits".
    pub cache_read_input_tokens: Option<u64>,
}

impl SessionUsage {
    /// Add usage from a turn
    pub fn add(&mut self, usage: &Usage) {
        self.input_tokens += u64::from(usage.input_tokens);
        self.output_tokens += u64::from(usage.output_tokens);
        if let Some(tokens) = usage.prompt_cache_miss_tokens {
            self.cache_creation_input_tokens =
                Some(self.cache_creation_input_tokens.unwrap_or(0) + u64::from(tokens));
        }
        if let Some(tokens) = usage.prompt_cache_hit_tokens {
            self.cache_read_input_tokens =
                Some(self.cache_read_input_tokens.unwrap_or(0) + u64::from(tokens));
        }
    }
}

impl Session {
    /// Create a new session
    pub fn new(
        model: String,
        workspace: PathBuf,
        allow_shell: bool,
        trust_mode: bool,
        notes_path: PathBuf,
        mcp_config_path: PathBuf,
    ) -> Self {
        // Load project context from AGENTS.md, CLAUDE.md, etc.
        let project_context = load_project_context_with_parents(&workspace);
        let has_context = project_context.has_instructions();

        Self {
            model,
            reasoning_effort: None,
            reasoning_effort_auto: false,
            auto_model: false,
            workspace: workspace.clone(),
            cwd: workspace,
            system_prompt: None,
            system_prompt_override: false,
            compaction_summary_prompt: None,
            messages: Vec::new(),
            recent_read_files: VecDeque::new(),
            total_usage: SessionUsage::default(),
            allow_shell,
            trust_mode,
            auto_approve: false,
            approval_mode: ApprovalMode::Suggest,
            notes_path,
            mcp_config_path,
            id: uuid::Uuid::new_v4().to_string(),
            project_context: if has_context {
                Some(project_context)
            } else {
                None
            },
            last_system_prompt_hash: None,
            working_set: WorkingSet::default(),
            cycle_count: 0,
            current_cycle_started: Utc::now(),
            cycle_briefings: Vec::new(),
            prefix_stability: None,
            micro_compact_state: MicroCompactState::default(),
            session_memory_compact_config: SessionMemoryCompactConfig::default(),
            circuit_breaker: CompactionCircuitBreaker::new(),
            responsive_compact_state: ResponsiveCompactState::new(),
        }
    }

    /// Add a message to the conversation
    pub fn add_message(&mut self, message: Message) {
        self.messages.push(message);
    }

    /// Rebuild the working set from current messages (best effort).
    pub fn rebuild_working_set(&mut self) {
        self.working_set
            .rebuild_from_messages(&self.messages, &self.workspace);
    }

    /// Record a successful `read_file` output for post-compaction reminders.
    pub fn record_read_file_result(&mut self, input: &Value, output_for_context: &str) {
        let Some(path) = input.get("path").and_then(Value::as_str) else {
            return;
        };
        let preview = summarize_chars(output_for_context, RECENT_READ_FILE_SNIPPET_CHARS);
        if let Some(existing) = self
            .recent_read_files
            .iter()
            .position(|entry| entry.path == path)
        {
            self.recent_read_files.remove(existing);
        }
        self.recent_read_files.push_back(RecentReadFile {
            path: path.to_string(),
            input: input.clone(),
            output_preview: preview,
        });
        while self.recent_read_files.len() > RECENT_READ_FILE_LIMIT {
            self.recent_read_files.pop_front();
        }
    }
}

fn summarize_chars(text: &str, limit: usize) -> String {
    if text.chars().count() <= limit {
        return text.to_string();
    }
    let take = limit.saturating_sub(3);
    let mut out: String = text.chars().take(take).collect();
    out.push_str("...");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn session_usage_cache_starts_none() {
        let usage = SessionUsage::default();
        assert!(usage.cache_creation_input_tokens.is_none());
        assert!(usage.cache_read_input_tokens.is_none());
    }

    #[test]
    fn session_usage_cache_remains_none_when_api_omits_cache() {
        let mut usage = SessionUsage::default();
        let api_usage = Usage {
            input_tokens: 100,
            output_tokens: 50,
            prompt_cache_hit_tokens: None,
            prompt_cache_miss_tokens: None,
            reasoning_tokens: None,
            reasoning_replay_tokens: None,
            server_tool_use: None,
        };
        usage.add(&api_usage);
        assert!(usage.cache_creation_input_tokens.is_none());
        assert!(usage.cache_read_input_tokens.is_none());
    }

    #[test]
    fn session_usage_cache_accumulates_when_reported() {
        let mut usage = SessionUsage::default();
        let api_usage = Usage {
            input_tokens: 100,
            output_tokens: 50,
            prompt_cache_hit_tokens: Some(30),
            prompt_cache_miss_tokens: Some(70),
            reasoning_tokens: None,
            reasoning_replay_tokens: None,
            server_tool_use: None,
        };
        usage.add(&api_usage);
        assert_eq!(usage.cache_read_input_tokens, Some(30));
        assert_eq!(usage.cache_creation_input_tokens, Some(70));
        usage.add(&api_usage);
        assert_eq!(usage.cache_read_input_tokens, Some(60));
        assert_eq!(usage.cache_creation_input_tokens, Some(140));
    }

    #[test]
    fn session_usage_cache_preserves_explicit_zero() {
        let mut usage = SessionUsage::default();
        let api_usage = Usage {
            input_tokens: 100,
            output_tokens: 50,
            prompt_cache_hit_tokens: Some(0), // explicit zero from provider
            prompt_cache_miss_tokens: Some(1234),
            reasoning_tokens: None,
            reasoning_replay_tokens: None,
            server_tool_use: None,
        };
        usage.add(&api_usage);
        // 0 is a valid observed value, must NOT be converted to None
        assert_eq!(usage.cache_read_input_tokens, Some(0));
        assert_eq!(usage.cache_creation_input_tokens, Some(1234));
    }

    #[test]
    fn record_read_file_result_tracks_latest_entry_by_path() {
        let mut session = Session::new(
            "test-model".to_string(),
            std::path::PathBuf::from("/tmp/workspace"),
            false,
            false,
            std::path::PathBuf::from("/tmp/notes.md"),
            std::path::PathBuf::from("/tmp/mcp.json"),
        );

        session.record_read_file_result(
            &serde_json::json!({"path": "src/lib.rs", "offset": 0}),
            "old contents",
        );
        session.record_read_file_result(
            &serde_json::json!({"path": "src/lib.rs", "offset": 10}),
            "new contents",
        );

        assert_eq!(session.recent_read_files.len(), 1);
        let entry = session.recent_read_files.back().unwrap();
        assert_eq!(entry.path, "src/lib.rs");
        assert_eq!(entry.input["offset"], 10);
        assert_eq!(entry.output_preview, "new contents");
    }

    #[test]
    fn record_read_file_result_ignores_missing_path() {
        let mut session = Session::new(
            "test-model".to_string(),
            std::path::PathBuf::from("/tmp/workspace"),
            false,
            false,
            std::path::PathBuf::from("/tmp/notes.md"),
            std::path::PathBuf::from("/tmp/mcp.json"),
        );

        session.record_read_file_result(&serde_json::json!({"file": "src/lib.rs"}), "contents");

        assert!(session.recent_read_files.is_empty());
    }

    #[test]
    fn record_read_file_result_bounds_and_truncates_recent_files() {
        let mut session = Session::new(
            "test-model".to_string(),
            std::path::PathBuf::from("/tmp/workspace"),
            false,
            false,
            std::path::PathBuf::from("/tmp/notes.md"),
            std::path::PathBuf::from("/tmp/mcp.json"),
        );
        let long_output = "é".repeat(RECENT_READ_FILE_SNIPPET_CHARS + 10);

        for index in 0..(RECENT_READ_FILE_LIMIT + 2) {
            session.record_read_file_result(
                &serde_json::json!({"path": format!("src/file_{index}.rs")}),
                &long_output,
            );
        }

        assert_eq!(session.recent_read_files.len(), RECENT_READ_FILE_LIMIT);
        assert_eq!(
            session.recent_read_files.front().unwrap().path,
            "src/file_2.rs"
        );
        assert_eq!(
            session.recent_read_files.back().unwrap().path,
            "src/file_13.rs"
        );
        assert_eq!(
            session
                .recent_read_files
                .back()
                .unwrap()
                .output_preview
                .chars()
                .count(),
            RECENT_READ_FILE_SNIPPET_CHARS
        );
        assert!(
            session
                .recent_read_files
                .back()
                .unwrap()
                .output_preview
                .ends_with("...")
        );
    }
}
